/**
 * /terms — placeholder legal content. Replace with your final Terms of
 * Service. Recommended: get a lawyer or use Terms-of-Service-generator
 * services like termly.io.
 */
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service · DebateThis",
  description: "The terms under which you use DebateThis.",
};

const UPDATED = "May 28, 2026";

export default function TermsPage() {
  return (
    <article className="space-y-6 leading-relaxed">
      <header className="border-b-[3px] border-double border-ink pb-4">
        <span className="font-condensed text-xs uppercase tracking-[0.28em] text-red">
          Legal
        </span>
        <h1 className="mt-1 font-display text-3xl">Terms of Service</h1>
        <p className="text-sm text-sepia">Last updated {UPDATED}</p>
      </header>

      <p>
        By using DebateThis (the "Service"), you agree to these Terms. If
        you don't agree, don't use the Service.
      </p>

      <Section title="1. The Service">
        <p>
          DebateThis is a 1v1 debate platform where users compete in
          structured arguments with audience voting, Elo-rated outcomes,
          and bot opponents. The Service is provided as-is, without
          warranty.
        </p>
      </Section>

      <Section title="2. Your account">
        <p>
          You're responsible for everything that happens under your account.
          Don't share your password. We don't store it in plaintext; we
          can't recover it for you.
        </p>
      </Section>

      <Section title="3. Content rules">
        <p>You agree not to post content that is:</p>
        <ul className="ml-6 list-disc">
          <li>Harassment or hate speech targeting individuals or groups.</li>
          <li>Threats of violence.</li>
          <li>Spam or copy-pasted from elsewhere without attribution.</li>
          <li>Plagiarism — passing off another's argument as your own.</li>
          <li>Generated by an LLM and submitted as your own work in human-vs-human matches.</li>
        </ul>
        <p>
          Violations may result in argument removal, account warnings, or
          bans, at our discretion.
        </p>
      </Section>

      <Section title="4. Bots and automated play">
        <p>
          Bot accounts must be clearly marked as such (username ending in
          `_bot`) and operate via the documented API. Bots may not
          impersonate humans in human-vs-human matchmaking.
        </p>
      </Section>

      <Section title="5. Data + privacy">
        <p>
          Our handling of your data is covered in our{" "}
          <Link href="/privacy" className="text-red underline">
            Privacy Policy
          </Link>
          . You can delete your account at any time from the Settings page.
          Past debate transcripts may persist (with your username scrubbed)
          to preserve opponents' Elo and audience-vote histories.
        </p>
      </Section>

      <Section title="6. Changes to these terms">
        <p>
          We may update these terms. We'll surface the change via in-app
          notice. Continued use after a change means acceptance of the new
          terms.
        </p>
      </Section>

      <Section title="7. Contact">
        <p>
          Questions? Email us. <em>(Address goes here.)</em>
        </p>
      </Section>

      <p className="text-xs text-sepia">
        This template is a starting point, not legal advice. Replace with a
        lawyer-reviewed Terms of Service before launch.
      </p>
    </article>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="font-display text-xl text-ink">{title}</h2>
      {children}
    </section>
  );
}
